import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import LanguageToggle from "@/components/LanguageToggle";
import { characters } from "@/data/characters";
import { summarizeYear } from "@/features/progression";
import { useActivityLedger } from "@/hooks/use-activity-ledger";
import { useLanguage } from "@/hooks/use-language";
import { useProfile } from "@/hooks/use-profile";

export default function AnnualSummaryScreen(){const{text,language}=useLanguage();const{events}=useActivityLedger();const{profile}=useProfile();const year=new Date().getFullYear();const summary=summarizeYear(events,year);const character=characters.find((item)=>item.id===summary.closestCharacterId);const characterName=character?(language==="zh"?(character.displayNameZh??character.displayName):character.displayName):text("Not enough history yet","尚无足够记录");const joinedDays=Math.max(1,Math.ceil((Date.now()-new Date(profile.createdAt).getTime())/86400000));const stats=[["✦",summary.totalEvents,text("recorded moments","条真实记录")],["☏",summary.chats,text("conversations","次对话")],["✉",summary.mailsRead,text("letters read","封已读邮件")],["◇",summary.outfitsEquipped,text("outfits changed","次换装")],["▦",summary.gamesCompleted,text("games completed","局游戏")],["✓",summary.tasksCompleted,text("tasks completed","项完成任务")],["♡",summary.healthDays,text("health days","个健康记录日")],["♜",summary.achievements,text("achievements","项成就")]];return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ {text("Me","我的")}</Text></Pressable><LanguageToggle/></View><View style={styles.hero}><Text style={styles.year}>{year}</Text><Text style={styles.title}>{text("Your year with IP Alive","你与 IP Alive 的这一年")}</Text><Text style={styles.lead}>{text(`${joinedDays} days since this profile's story began. Every number below comes from a dated action in the local activity ledger.`,`这个档案的故事已开始 ${joinedDays} 天。下方每个数字都来自本地时间线中带日期的真实行动。`)}</Text></View><View style={styles.grid}>{stats.map(([icon,value,label])=><View key={String(label)} style={styles.stat}><Text style={styles.icon}>{icon}</Text><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>)}</View><View style={styles.bond}><Text style={styles.bondEyebrow}>{text("CLOSEST COMPANION","最亲近的伙伴")}</Text><Text style={styles.bondName}>{characterName}</Text><Text style={styles.bondText}>{text("Calculated from chats, mail, outfits, games, journeys and Life actions recorded this year.","根据今年记录的聊天、邮件、换装、游戏、旅行和生活行动计算。")}</Text></View><View style={styles.note}><Text style={styles.noteTitle}>{text("About this version","关于这一版本")}</Text><Text style={styles.noteText}>{text("The dated ledger starts with actions performed after this update. Older aggregate totals are not assigned invented dates, so future annual stories remain trustworthy.","带日期的时间线从本次更新后的新行动开始。旧版只有累计值的数据不会被虚构日期，因此未来的年度故事仍然可信。")}</Text></View></ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#F4F0F8"},content:{padding:20,paddingTop:56,paddingBottom:52},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:15,fontWeight:"800",color:"#6A4FD3"},hero:{marginTop:20,padding:22,borderRadius:27,backgroundColor:"#2B2041"},year:{fontSize:11,fontWeight:"900",letterSpacing:2,color:"#BDAAFF"},title:{marginTop:7,fontSize:27,lineHeight:33,fontWeight:"900",color:"#FFF"},lead:{marginTop:10,fontSize:11,lineHeight:18,color:"#D9CFE5"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:14},stat:{width:"48%",padding:16,borderRadius:20,backgroundColor:"#FFF"},icon:{fontSize:17,color:"#7659D4"},value:{marginTop:7,fontSize:27,fontWeight:"900",color:"#332B39"},label:{marginTop:2,fontSize:9,color:"#7A7280"},bond:{marginTop:14,padding:20,borderRadius:23,backgroundColor:"#E1F1EA"},bondEyebrow:{fontSize:9,fontWeight:"900",letterSpacing:1.3,color:"#4B7A68"},bondName:{marginTop:5,fontSize:25,fontWeight:"900",color:"#294D40"},bondText:{marginTop:5,fontSize:10,lineHeight:16,color:"#608073"},note:{marginTop:14,padding:17,borderRadius:20,backgroundColor:"#FFF0C9"},noteTitle:{fontSize:12,fontWeight:"900",color:"#735714"},noteText:{marginTop:5,fontSize:9,lineHeight:15,color:"#7C6A3D"}});
