import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import LanguageToggle from "@/components/LanguageToggle";
import { exportDeviceBackup, hasRollbackSnapshot, importDeviceBackup, restorePreviousSnapshot } from "@/features/persistence";
import { useLanguage } from "@/hooks/use-language";

export default function DataManagementScreen() {
  const { text } = useLanguage(); const [busy,setBusy]=useState(false); const [rollback,setRollback]=useState(false); const [lastAction,setLastAction]=useState("");
  useEffect(()=>{void hasRollbackSnapshot().then(setRollback)},[]);
  const run=async(action:()=>Promise<void>)=>{setBusy(true);try{await action()}catch(error){const reason=error instanceof Error?error.message:"unknown";Alert.alert(text("Could not complete the action","操作未完成"),reason)}finally{setBusy(false)}};
  const exportData=()=>run(async()=>{const payload=await exportDeviceBackup();setLastAction(text(`Backup exported · ${payload.exportedAt.slice(0,16).replace("T"," ")}`,`备份已导出 · ${payload.exportedAt.slice(0,16).replace("T"," ")}`))});
  const chooseImport=()=>Alert.alert(text("Replace current local data?","替换当前本地数据？"),text("A valid backup will replace account, Life and character progress. A rollback snapshot will be saved first.","有效备份将替换账号、Life 和角色进度；覆盖前会自动保留回滚快照。"),[{text:text("Cancel","取消"),style:"cancel"},{text:text("Choose backup","选择备份"),onPress:()=>void run(async()=>{const payload=await importDeviceBackup();if(!payload)return;setRollback(true);setLastAction(text("Backup restored. Fully close and reopen the app to load it.","备份已恢复。请彻底关闭并重新打开 App 以载入数据。"))})}]);
  const undoImport=()=>Alert.alert(text("Restore the pre-import snapshot?","恢复导入前的数据？"),text("This replaces the currently stored data with the automatic snapshot created before the last import.","这会使用上次导入前自动保存的快照替换当前数据。"),[{text:text("Cancel","取消"),style:"cancel"},{text:text("Restore","恢复"),style:"destructive",onPress:()=>void run(async()=>{if(await restorePreviousSnapshot())setLastAction(text("Previous snapshot restored. Reopen the app.","导入前快照已恢复，请重新打开 App。"))})}]);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ {text("Me","我的")}</Text></Pressable><LanguageToggle/></View>
    <Text style={styles.eyebrow}>LOCAL DATA VAULT</Text><Text style={styles.title}>{text("Backup & recovery","备份与恢复")}</Text><Text style={styles.subtitle}>{text("Keep a portable copy of your progress before changing devices or testing a new build.","在更换设备或测试新版本前，为全部进度保留一份可携带副本。")}</Text>
    <View style={styles.coverage}><Text style={styles.coverageTitle}>{text("Included in every backup","每份备份包含")}</Text>{[["◎",text("Profile identity, registration date and activity timeline","账号身份、注册日期与活动时间线")],["▦",text("Character ownership, product fingerprints and unlock dates","角色资产、商品指纹与解锁日期")],["☏",text("Saved local conversations and recent conversation memories","已保存的本地对话与近期对话回忆")],["◉",text("Bubble, EXP, game rewards and shop unlocks","Bubble、EXP、游戏奖励和商店解锁")],["♥",text("Bond points, interaction history and generated mail","好感度、互动历史和动态邮件")],["✓",text("Tasks, expenses, goals, meals, weight and achievements","任务、支出、目标、餐次、体重与成就")]].map(([icon,label])=><View key={label} style={styles.coverageRow}><Text style={styles.coverageIcon}>{icon}</Text><Text style={styles.coverageText}>{label}</Text></View>)}</View>
    <Pressable disabled={busy} style={[styles.primary,busy&&styles.disabled]} onPress={()=>void exportData()}><Text style={styles.primaryIcon}>⇧</Text><View style={{flex:1}}><Text style={styles.primaryTitle}>{text("Export backup file","导出备份文件")}</Text><Text style={styles.primaryText}>{text("Save to Files, AirDrop or another secure location","保存到“文件”、隔空投送或其他安全位置")}</Text></View></Pressable>
    <Pressable disabled={busy} style={[styles.secondary,busy&&styles.disabled]} onPress={chooseImport}><Text style={styles.secondaryIcon}>⇩</Text><View style={{flex:1}}><Text style={styles.secondaryTitle}>{text("Import backup file","导入备份文件")}</Text><Text style={styles.secondaryText}>{text("Only verified IP Alive JSON backups are accepted","仅接受通过校验的 IP Alive JSON 备份")}</Text></View></Pressable>
    {rollback&&<Pressable disabled={busy} style={styles.rollback} onPress={undoImport}><Text style={styles.rollbackTitle}>{text("Undo the last import","撤销上次导入")}</Text><Text style={styles.rollbackText}>{text("Restore the automatic pre-import snapshot","恢复导入前自动生成的快照")}</Text></Pressable>}
    {lastAction&&<View style={styles.status}><Text style={styles.statusText}>{lastAction}</Text></View>}
    <View style={styles.warning}><Text style={styles.warningTitle}>{text("Private file","私人文件")}</Text><Text style={styles.warningText}>{text("The backup is not encrypted and may contain spending, health and conversation progress. Store it somewhere you trust and do not send it to strangers.","备份文件未加密，可能包含消费、健康和互动进度。请保存在可信位置，不要发送给陌生人。")}</Text></View>
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#F5F2F8"},content:{padding:20,paddingTop:56,paddingBottom:48},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:15,fontWeight:"800",color:"#6B50D8"},eyebrow:{marginTop:25,fontSize:9,fontWeight:"900",letterSpacing:1.5,color:"#6B50D8"},title:{marginTop:5,fontSize:29,fontWeight:"900",color:"#2E2834"},subtitle:{marginTop:7,fontSize:12,lineHeight:18,color:"#77707D"},coverage:{marginTop:20,padding:18,borderRadius:22,backgroundColor:"#29203F"},coverageTitle:{marginBottom:10,fontSize:14,fontWeight:"900",color:"#FFF"},coverageRow:{flexDirection:"row",alignItems:"center",marginTop:8},coverageIcon:{width:27,fontSize:15,fontWeight:"900",color:"#BFAEFF"},coverageText:{flex:1,fontSize:10,lineHeight:15,color:"#D3C9DF"},primary:{flexDirection:"row",alignItems:"center",marginTop:14,padding:17,borderRadius:21,backgroundColor:"#6B50D8"},primaryIcon:{marginRight:14,fontSize:28,fontWeight:"800",color:"#FFF"},primaryTitle:{fontSize:14,fontWeight:"900",color:"#FFF"},primaryText:{marginTop:3,fontSize:9,color:"#D9D0FF"},secondary:{flexDirection:"row",alignItems:"center",marginTop:10,padding:17,borderRadius:21,backgroundColor:"#E7E0FA"},secondaryIcon:{marginRight:14,fontSize:28,fontWeight:"800",color:"#5B46B3"},secondaryTitle:{fontSize:14,fontWeight:"900",color:"#46376D"},secondaryText:{marginTop:3,fontSize:9,color:"#776B91"},rollback:{marginTop:10,padding:15,borderRadius:18,borderWidth:1,borderColor:"#D7A5AA",backgroundColor:"#FFF4F3"},rollbackTitle:{fontSize:12,fontWeight:"900",color:"#8E4D55"},rollbackText:{marginTop:3,fontSize:9,color:"#9A6C72"},status:{marginTop:12,padding:14,borderRadius:17,backgroundColor:"#DFF2E8"},statusText:{fontSize:10,lineHeight:15,fontWeight:"700",color:"#356450"},warning:{marginTop:18,padding:16,borderRadius:19,backgroundColor:"#FFF0C9"},warningTitle:{fontSize:11,fontWeight:"900",color:"#705510"},warningText:{marginTop:5,fontSize:9,lineHeight:15,color:"#796A40"},disabled:{opacity:.5}});
