import { Image } from "expo-image";
import * as ImagePicker from "expo-image-picker";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import LanguageToggle from "@/components/LanguageToggle";
import { calculateNutrition, FOOD_CATALOG, persistMealPhoto, searchFoods } from "@/features/nutrition";
import { useLanguage } from "@/hooks/use-language";
import { type MealType, useLifeProgress } from "@/hooks/use-life-progress";

export default function MealCameraScreen(){const{text,language}=useLanguage();const life=useLifeProgress();const[photoUri,setPhotoUri]=useState<string>();const[query,setQuery]=useState("");const[foodId,setFoodId]=useState(FOOD_CATALOG[0].id);const[grams,setGrams]=useState(`${FOOD_CATALOG[0].servingGrams}`);const[type,setType]=useState<MealType>("lunch");const food=FOOD_CATALOG.find((item)=>item.id===foodId)??FOOD_CATALOG[0];const amount=useMemo(()=>calculateNutrition(food,Number(grams)||0),[food,grams]);
  useEffect(()=>{void ImagePicker.getPendingResultAsync().then((result)=>{if(result&&"canceled" in result&&!result.canceled&&result.assets?.[0])setPhotoUri(result.assets[0].uri)})},[]);
  const accept=(result:ImagePicker.ImagePickerResult)=>{if(!result.canceled&&result.assets[0])setPhotoUri(result.assets[0].uri)};
  const camera=async()=>{const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted){Alert.alert(text("Camera permission needed","需要相机权限"),text("You can still choose a photo from the library.","你仍可从相册选择照片。"));return}accept(await ImagePicker.launchCameraAsync({mediaTypes:["images"],quality:.75,cameraType:ImagePicker.CameraType.back}))};
  const library=async()=>accept(await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:.75}));
  const save=()=>{if(!photoUri||!(Number(grams)>0))return;try{const stored=persistMealPhoto(photoUri);life.addCatalogMeal(type,food.id,Number(grams),stored);router.back()}catch(error){Alert.alert(text("Could not save photo","照片保存失败"),error instanceof Error?error.message:"")}};
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ {text("Life","生活")}</Text></Pressable><LanguageToggle/></View><Text style={styles.eyebrow}>PHOTO MEAL LOG</Text><Text style={styles.title}>{text("Estimate, then confirm","拍照估算，再由你确认")}</Text><Text style={styles.subtitle}>{text("This free local build does not pretend to recognize pixels with AI. The photo anchors your memory; you confirm the food and portion before anything is recorded.","此免费本地版本不会假装使用 AI 识别图片。照片用于帮助回忆，食物和份量必须由你确认后才会记录。")}</Text>
    <View style={styles.photo}>{photoUri?<Image source={{uri:photoUri}} style={styles.image} contentFit="cover"/>:<View style={styles.empty}><Text style={styles.cameraIcon}>⌾</Text><Text style={styles.emptyText}>{text("Take or choose a meal photo","拍摄或选择一张餐食照片")}</Text></View>}</View><View style={styles.photoActions}><Pressable style={styles.photoButton} onPress={()=>void camera()}><Text style={styles.photoButtonText}>{text("TAKE PHOTO","拍照")}</Text></Pressable><Pressable style={styles.photoButton} onPress={()=>void library()}><Text style={styles.photoButtonText}>{text("CHOOSE PHOTO","选择照片")}</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.cardTitle}>{text("1 · Meal type","1 · 餐次")}</Text><View style={styles.types}>{(["breakfast","lunch","dinner","snack"] as MealType[]).map((item)=><Pressable key={item} onPress={()=>setType(item)} style={[styles.type,type===item&&styles.active]}><Text style={styles.typeText}>{text(item.toUpperCase(),{breakfast:"早餐",lunch:"午餐",dinner:"晚餐",snack:"加餐"}[item])}</Text></Pressable>)}</View><Text style={styles.cardTitle}>{text("2 · Confirm food","2 · 确认食物")}</Text><TextInput value={query} onChangeText={setQuery} placeholder={text("Search the local catalog","搜索本地食物库")} placeholderTextColor="#958D9A" style={styles.input}/><View style={styles.foods}>{searchFoods(query,language).map((item)=><Pressable key={item.id} onPress={()=>{setFoodId(item.id);setGrams(`${item.servingGrams}`)}} style={[styles.food,item.id===food.id&&styles.foodActive]}><Text style={[styles.foodName,item.id===food.id&&styles.foodNameActive]}>{language==="zh"?item.nameZh:item.nameEn}</Text><Text style={styles.serving}>{item.servingGrams}g</Text></Pressable>)}</View><Text style={styles.cardTitle}>{text("3 · Confirm portion","3 · 确认份量")}</Text><TextInput value={grams} onChangeText={setGrams} keyboardType="decimal-pad" style={styles.input}/><View style={styles.result}><Text style={styles.calories}>{amount.calories} kcal</Text><Text style={styles.macros}>P {amount.protein}g · C {amount.carbs}g · F {amount.fat}g</Text></View></View>
    <View style={styles.notice}><Text style={styles.noticeTitle}>{text("Estimate—not a measurement","这是估算，不是测量")}</Text><Text style={styles.noticeText}>{text("Cooking oil, sauces and hidden ingredients may not be represented. Meal photos remain on this device and are not included in portable JSON backups.","烹饪油、酱汁和隐藏食材可能未被计入。餐食照片仅保存在本设备，不包含在可携带的 JSON 备份中。")}</Text></View><Pressable disabled={!photoUri||!(Number(grams)>0)} onPress={save} style={[styles.save,(!photoUri||!(Number(grams)>0))&&styles.disabled]}><Text style={styles.saveText}>{text("Save confirmed estimate","保存确认后的估算")}</Text></Pressable></ScrollView>}

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#F5F2F8"},content:{padding:19,paddingTop:56,paddingBottom:50},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:15,fontWeight:"900",color:"#6B50D8"},eyebrow:{marginTop:22,fontSize:9,fontWeight:"900",letterSpacing:1.5,color:"#6B50D8"},title:{marginTop:5,fontSize:27,fontWeight:"900",color:"#2F2935"},subtitle:{marginTop:7,fontSize:10,lineHeight:16,color:"#746D79"},photo:{height:240,marginTop:16,overflow:"hidden",borderRadius:24,backgroundColor:"#E3DEE7"},image:{width:"100%",height:"100%"},empty:{flex:1,alignItems:"center",justifyContent:"center"},cameraIcon:{fontSize:48,color:"#7963C8"},emptyText:{marginTop:8,fontSize:11,fontWeight:"800",color:"#776E7D"},photoActions:{flexDirection:"row",gap:8,marginTop:9},photoButton:{flex:1,alignItems:"center",padding:12,borderRadius:14,backgroundColor:"#E5DDF8"},photoButtonText:{fontSize:9,fontWeight:"900",color:"#5C47AD"},card:{marginTop:14,padding:16,borderRadius:22,backgroundColor:"#FFF"},cardTitle:{marginTop:5,marginBottom:8,fontSize:12,fontWeight:"900",color:"#403847"},types:{flexDirection:"row",gap:5,marginBottom:14},type:{flex:1,alignItems:"center",paddingVertical:8,borderRadius:10,backgroundColor:"#EEEAF1"},active:{backgroundColor:"#DCD2FF"},typeText:{fontSize:7,fontWeight:"900",color:"#5D5366"},input:{marginBottom:9,paddingHorizontal:13,paddingVertical:12,borderRadius:13,backgroundColor:"#F1EEF3",fontSize:13,color:"#312B37"},foods:{flexDirection:"row",flexWrap:"wrap",gap:6,marginBottom:14},food:{width:"48%",padding:10,borderRadius:12,backgroundColor:"#F0ECF3"},foodActive:{backgroundColor:"#6550C2"},foodName:{fontSize:8,fontWeight:"900",color:"#514958"},foodNameActive:{color:"#FFF"},serving:{marginTop:3,fontSize:7,color:"#968B9D"},result:{padding:14,borderRadius:15,backgroundColor:"#E3F2EA"},calories:{fontSize:22,fontWeight:"900",color:"#315B48"},macros:{marginTop:4,fontSize:9,color:"#627D70"},notice:{marginTop:12,padding:14,borderRadius:18,backgroundColor:"#FFF0C9"},noticeTitle:{fontSize:10,fontWeight:"900",color:"#705510"},noticeText:{marginTop:5,fontSize:8,lineHeight:14,color:"#796A40"},save:{alignItems:"center",marginTop:12,padding:15,borderRadius:17,backgroundColor:"#684FD2"},saveText:{fontSize:12,fontWeight:"900",color:"#FFF"},disabled:{opacity:.4}});
