import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext,type ReactNode,useContext,useEffect,useMemo,useState } from "react";
import { characterStoryEvents,getStoryProgress,type CharacterStoryEvent } from "@/features/characters";
import { useActivityLedger } from "@/hooks/use-activity-ledger";
import { useAffinity } from "@/hooks/use-affinity";
import { useGameProgress } from "@/hooks/use-game-progress";
interface StoryValue{claimedIds:string[];getState:(event:CharacterStoryEvent)=>ReturnType<typeof getStoryProgress>&{claimed:boolean};claim:(event:CharacterStoryEvent)=>boolean}
const Context=createContext<StoryValue|undefined>(undefined);
export function StoryEventsProvider({children}:{children:ReactNode}){const{events}=useActivityLedger();const affinity=useAffinity();const account=useGameProgress();const[claimedIds,setClaimedIds]=useState<string[]>([]);const[hydrated,setHydrated]=useState(false);useEffect(()=>{void AsyncStorage.getItem("ip-alive:story-events:v1").then((raw)=>{if(raw)setClaimedIds(JSON.parse(raw).claimedIds??[])}).finally(()=>setHydrated(true))},[]);useEffect(()=>{if(hydrated)void AsyncStorage.setItem("ip-alive:story-events:v1",JSON.stringify({schemaVersion:1,claimedIds}))},[claimedIds,hydrated]);useEffect(()=>{if(!hydrated)return;characterStoryEvents.forEach((event)=>{const progress=getStoryProgress(event,events);progress.objectives.forEach((objective,index)=>{if(!objective.complete)return;const copy=event.stageMails[index];if(copy)affinity.deliverMail({id:`story-${event.id}-${index+1}`,characterId:event.characterId,kind:"event",sentAt:new Date().toISOString(),...copy})})})},[events,hydrated,affinity]);const value=useMemo<StoryValue>(()=>({claimedIds,getState:(event)=>({...getStoryProgress(event,events),claimed:claimedIds.includes(event.id)}),claim:(event)=>{const progress=getStoryProgress(event,events);if(!progress.completed||claimedIds.includes(event.id))return false;setClaimedIds((current)=>[...current,event.id]);account.addLifeReward(event.rewardBubbles,120);affinity.award(event.characterId,event.rewardBond,"journey",`story-${event.id}`);return true}}),[events,claimedIds,account,affinity]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useStoryEvents(){const value=useContext(Context);if(!value)throw new Error("useStoryEvents must be used inside StoryEventsProvider");return value}
