import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext,type ReactNode,useContext,useEffect,useMemo,useState } from "react";
import { DEMO_SEED_CHARACTER_IDS,tokenFingerprint,validateOfflineDemoCode,type LocalUnlockGrant,type UnlockResult } from "@/features/unlock";
import { useActivityLedger } from "@/hooks/use-activity-ledger";
interface UnlockValue{grants:LocalUnlockGrant[];isUnlocked:(characterId:string)=>boolean;redeemOfflineCode:(code:string)=>UnlockResult;}
const STORAGE_KEY="ip-alive:unlocks:v1";const Context=createContext<UnlockValue|undefined>(undefined);
const seedGrants=()=>DEMO_SEED_CHARACTER_IDS.map((characterId):LocalUnlockGrant=>({characterId,productId:`demo-seed-${characterId}`,tokenFingerprint:`seed-${characterId}`,unlockedAt:"2026-07-24T00:00:00.000Z",source:"demo-seed"}));
export function UnlockProvider({children}:{children:ReactNode}){const activity=useActivityLedger();const[grants,setGrants]=useState<LocalUnlockGrant[]>(seedGrants);const[hydrated,setHydrated]=useState(false);useEffect(()=>{void AsyncStorage.getItem(STORAGE_KEY).then((raw)=>{if(raw){const saved=JSON.parse(raw);setGrants(saved.grants??seedGrants())}}).finally(()=>setHydrated(true))},[]);useEffect(()=>{if(hydrated)void AsyncStorage.setItem(STORAGE_KEY,JSON.stringify({schemaVersion:1,grants}))},[grants,hydrated]);const value=useMemo<UnlockValue>(()=>({grants,isUnlocked:(characterId)=>grants.some((grant)=>grant.characterId===characterId),redeemOfflineCode:(code)=>{const checked=validateOfflineDemoCode(code,grants);if(checked.result.status!=="unlocked"||!checked.definition)return checked.result;const unlockedAt=checked.result.unlockedAt??new Date().toISOString();const grant:LocalUnlockGrant={characterId:checked.definition.characterId,productId:checked.definition.productId,tokenFingerprint:tokenFingerprint(checked.definition.code),unlockedAt,source:"offline-code"};setGrants((current)=>[...current,grant]);activity.record("character-unlocked",checked.definition.characterId,{characterId:checked.definition.characterId,metadata:{productId:checked.definition.productId,channel:"offline-demo"}});return checked.result}}),[grants,activity]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useUnlocks(){const value=useContext(Context);if(!value)throw new Error("useUnlocks must be used inside UnlockProvider");return value}
