import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Notifications from "expo-notifications";
import { createContext, type ReactNode, useContext, useEffect, useMemo, useState } from "react";
import { Platform } from "react-native";

import { useGameProgress } from "@/hooks/use-game-progress";
import { useAffinity } from "@/hooks/use-affinity";
import { useLanguage } from "@/hooks/use-language";
import { renderCharacterLine } from "@/features/characters";

export type TaskRepeat = "none" | "daily" | "weekly";
export interface LifeTask { id: string; title: string; date: string; time: string; remindBefore: number; completed: boolean; createdAt: string; repeat: TaskRepeat; notificationId?: string; }
export interface Expense { id: string; amount: number; category: string; note: string; date: string; }
export type MealType = "breakfast" | "lunch" | "dinner" | "snack";
export interface MealEntry { id: string; type: MealType; calories: number; note: string; }
export interface HealthLog { id: string; intake: number; burned: number; weight?: number; date: string; meals: MealEntry[]; }
export interface LifeGoals { monthlyIncome: number; fixedCosts: number; savingsTarget: number; calorieTarget: number; currentWeight: number; targetWeight: number; targetDate: string; }
export interface LifeAchievement { id: string; earnedAt: string; bubbles: number; }

const today = () => new Date().toISOString().slice(0, 10);
const INITIAL_GOALS: LifeGoals = { monthlyIncome: 12000, fixedCosts: 5200, savingsTarget: 3000, calorieTarget: 1900, currentWeight: 72, targetWeight: 69, targetDate: "2026-10-31" };
interface LifeValue { tasks: LifeTask[]; expenses: Expense[]; healthLogs: HealthLog[]; goals: LifeGoals; achievements: LifeAchievement[]; remindersEnabled: boolean; setGoals: (goals: LifeGoals) => void; setReminders: (enabled: boolean) => Promise<boolean>; addTask: (title: string, date: string, repeat?: TaskRepeat, time?: string, remindBefore?: number) => void; updateTask: (id: string, title: string, date: string, repeat: TaskRepeat, time?: string, remindBefore?: number) => void; deleteTask: (id: string) => void; toggleTask: (id: string) => void; addExpense: (amount: number, category: string, note: string) => void; updateExpense: (id: string, amount: number, category: string, note: string) => void; deleteExpense: (id: string) => void; addHealthLog: (intake: number, burned: number, weight?: number) => void; addMeal: (type: MealType, calories: number, note: string) => void; }
const Context = createContext<LifeValue | undefined>(undefined);

Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldPlaySound: true, shouldSetBadge: false, shouldShowBanner: true, shouldShowList: true }) });
const nextDate = (date: string, repeat: TaskRepeat) => { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + (repeat === "daily" ? 1 : 7)); return value.toISOString().slice(0, 10); };
async function scheduleTask(task: Pick<LifeTask, "title" | "date" | "time" | "remindBefore">, characterId: string, language: "en" | "zh") { const date = new Date(`${task.date}T${task.time || "09:00"}:00`); date.setMinutes(date.getMinutes() - (task.remindBefore ?? 0)); if (date.getTime() <= Date.now()) return undefined; return Notifications.scheduleNotificationAsync({ content: { title: "IP Alive · Today", body: renderCharacterLine(characterId, "task-reminder", language, { task: task.title }), data: { url: "/life", characterId } }, trigger: { type: Notifications.SchedulableTriggerInputTypes.DATE, date } }); }

export function LifeProgressProvider({ children }: { children: ReactNode }) {
  const account = useGameProgress();
  const affinity = useAffinity();
  const { language } = useLanguage();
  const [tasks, setTasks] = useState<LifeTask[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [healthLogs, setHealthLogs] = useState<HealthLog[]>([]); const [goals, setGoals] = useState(INITIAL_GOALS); const [achievements, setAchievements] = useState<LifeAchievement[]>([]); const [remindersEnabled, setRemindersEnabled] = useState(false); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { void AsyncStorage.getItem("ip-alive:life-progress:v2").then(async (raw) => { const legacy = raw ?? await AsyncStorage.getItem("ip-alive:life-progress:v1"); if (!legacy) return; const saved = JSON.parse(legacy); setTasks((saved.tasks ?? []).map((task: Partial<LifeTask>) => ({ ...task, repeat: task.repeat ?? "none", time: task.time ?? "09:00", remindBefore: task.remindBefore ?? 0 })) as LifeTask[]); setExpenses(saved.expenses ?? []); setHealthLogs((saved.healthLogs ?? []).map((log: Partial<HealthLog>) => ({ ...log, meals: log.meals ?? [] })) as HealthLog[]); setGoals({ ...INITIAL_GOALS, ...saved.goals }); setAchievements(saved.achievements ?? []); setRemindersEnabled(saved.remindersEnabled ?? false); }).finally(() => setHydrated(true)); }, []);
  useEffect(() => { if (hydrated) void AsyncStorage.setItem("ip-alive:life-progress:v2", JSON.stringify({ schemaVersion: 2, tasks, expenses, healthLogs, goals, achievements, remindersEnabled })); }, [tasks, expenses, healthLogs, goals, achievements, remindersEnabled, hydrated]);
  const earn = (id: string, bubbles: number) => setAchievements((current) => { if (current.some((item) => item.id === id)) return current; account.addLifeReward(bubbles, 60); return [...current, { id, bubbles, earnedAt: new Date().toISOString() }]; });
  const value = useMemo<LifeValue>(() => ({ tasks, expenses, healthLogs, goals, achievements, remindersEnabled, setGoals,
    setReminders: async (enabled) => { if (!enabled) { await Notifications.cancelAllScheduledNotificationsAsync(); setRemindersEnabled(false); return true; } if (Platform.OS === "android") await Notifications.setNotificationChannelAsync("life", { name: "Life reminders", importance: Notifications.AndroidImportance.HIGH }); const result = await Notifications.requestPermissionsAsync(); if (result.status !== "granted") return false; setRemindersEnabled(true); const scheduled = await Promise.all(tasks.filter((task) => !task.completed).map(async (task) => ({ id: task.id, notificationId: await scheduleTask(task, account.selectedCharacterId, language) }))); setTasks((current) => current.map((task) => ({ ...task, notificationId: scheduled.find((item) => item.id === task.id)?.notificationId ?? task.notificationId }))); return true; },
    addTask: (title, date, repeat = "none", time = "09:00", remindBefore = 0) => { if (!title.trim()) return; const task: LifeTask = { id: `task-${Date.now()}`, title: title.trim(), date: date || today(), time, remindBefore, completed: false, repeat, createdAt: new Date().toISOString() }; setTasks((current) => [task, ...current]); if (remindersEnabled) void scheduleTask(task, account.selectedCharacterId, language).then((notificationId) => setTasks((current) => current.map((item) => item.id === task.id ? { ...item, notificationId } : item))); },
    updateTask: (id, title, date, repeat, time = "09:00", remindBefore = 0) => { const source = tasks.find((task) => task.id === id); if (!source || !title.trim()) return; if (source.notificationId) void Notifications.cancelScheduledNotificationAsync(source.notificationId); const updated = { ...source, title: title.trim(), date, repeat, time, remindBefore, notificationId: undefined }; setTasks((current) => current.map((task) => task.id === id ? updated : task)); earn("plan-adjuster", 60); if (remindersEnabled && !updated.completed) void scheduleTask(updated, account.selectedCharacterId, language).then((notificationId) => setTasks((current) => current.map((item) => item.id === id ? { ...item, notificationId } : item))); },
    deleteTask: (id) => { const source = tasks.find((task) => task.id === id); if (source?.notificationId) void Notifications.cancelScheduledNotificationAsync(source.notificationId); setTasks((current) => current.filter((task) => task.id !== id)); },
    toggleTask: (id) => { const source = tasks.find((task) => task.id === id); if (!source) return; const completing = !source.completed; const next = tasks.map((task) => task.id === id ? { ...task, completed: completing } : task); if (completing) { account.addAccountExperience(12); affinity.award(account.selectedCharacterId, 6, "life", `task-${id}`); } if (completing && source.notificationId) void Notifications.cancelScheduledNotificationAsync(source.notificationId); if (completing && source.repeat !== "none") { const repeated: LifeTask = { ...source, id: `task-${Date.now()}`, date: nextDate(source.date, source.repeat), completed: false, notificationId: undefined, createdAt: new Date().toISOString() }; next.unshift(repeated); if (remindersEnabled) void scheduleTask(repeated, account.selectedCharacterId, language).then((notificationId) => setTasks((current) => current.map((item) => item.id === repeated.id ? { ...item, notificationId } : item))); } setTasks(next); const completed = next.filter((task) => task.completed).length; if (completed >= 1) earn("first-step", 40); if (completed >= 3) earn("steady-three", 100); },
    addExpense: (amount, category, note) => { if (!(amount > 0)) return; const id = `expense-${Date.now()}`; const next = [{ id, amount, category, note: note.trim(), date: today() }, ...expenses]; setExpenses(next); account.addAccountExperience(4); affinity.award(account.selectedCharacterId, 2, "life", id); earn("budget-begins", 40); if (new Set(next.map((item) => item.category)).size >= 3) earn("category-aware", 90); },
    updateExpense: (id, amount, category, note) => { if (!(amount > 0)) return; setExpenses((current) => current.map((expense) => expense.id === id ? { ...expense, amount, category, note: note.trim() } : expense)); },
    deleteExpense: (id) => setExpenses((current) => current.filter((expense) => expense.id !== id)),
    addHealthLog: (intake, burned, weight) => { if (!(intake > 0 || burned > 0 || weight)) return; const existing = healthLogs.find((item) => item.date === today()); setHealthLogs((current) => [{ id: existing?.id ?? `health-${Date.now()}`, intake, burned, weight, date: today(), meals: existing?.meals ?? [] }, ...current.filter((item) => item.date !== today())]); account.addAccountExperience(6); affinity.award(account.selectedCharacterId, 3, "life", `health-${today()}`); earn("health-begins", 40); if (intake > 0 && Math.abs(intake - goals.calorieTarget) <= goals.calorieTarget * .1) earn("balanced-day", 80); },
    addMeal: (type, calories, note) => { if (!(calories > 0)) return; const existing = healthLogs.find((item) => item.date === today()); const meal = { id: `meal-${Date.now()}`, type, calories, note: note.trim() }; const meals = [...(existing?.meals ?? []), meal]; setHealthLogs((current) => [{ id: existing?.id ?? `health-${Date.now()}`, intake: meals.reduce((sum, item) => sum + item.calories, 0), burned: existing?.burned ?? 0, weight: existing?.weight, date: today(), meals }, ...current.filter((item) => item.date !== today())]); account.addAccountExperience(3); affinity.award(account.selectedCharacterId, 2, "life", meal.id); earn("health-begins", 40); },
  }), [tasks, expenses, healthLogs, goals, achievements, remindersEnabled, account, affinity, language]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}

export function useLifeProgress() { const value = useContext(Context); if (!value) throw new Error("useLifeProgress must be used inside LifeProgressProvider"); return value; }
