import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext,type ReactNode,useContext,useEffect,useMemo,useState } from "react";
import { getStoryEventPlacement,getStoryEvents,getStoryProgress,type CharacterStoryEvent } from "@/features/characters";
import { getActiveContentPack } from "@/features/content-packs";
import { useActivityLedger } from "@/hooks/use-activity-ledger";
import { getAffinityLevel,useAffinity } from "@/hooks/use-affinity";
import { useGameProgress } from "@/hooks/use-game-progress";
interface StoryValue{claimedIds:string[];getActiveEvent:(characterId:string)=>CharacterStoryEvent|undefined;getState:(event:CharacterStoryEvent)=>ReturnType<typeof getStoryProgress>&{claimed:boolean;locked:boolean;requiredBondLevel:number};claim:(event:CharacterStoryEvent)=>boolean}
const Context=createContext<StoryValue|undefined>(undefined);
export function StoryEventsProvider({children}:{children:ReactNode}){const{events}=useActivityLedger();const affinity=useAffinity();const account=useGameProgress();const[claimedIds,setClaimedIds]=useState<string[]>([]);const[claimedAt,setClaimedAt]=useState<Record<string,string>>({});const[hydrated,setHydrated]=useState(false);useEffect(()=>{void AsyncStorage.getItem("ip-alive:story-events:v1").then((raw)=>{if(raw){const parsed=JSON.parse(raw);const savedClaimedIds:string[]=parsed.claimedIds??[];const migrationTime=new Date().toISOString();setClaimedIds(savedClaimedIds);setClaimedAt(Object.fromEntries(savedClaimedIds.map((id)=>[id,parsed.claimedAt?.[id]??migrationTime])))}}).finally(()=>setHydrated(true))},[]);useEffect(()=>{if(hydrated)void AsyncStorage.setItem("ip-alive:story-events:v1",JSON.stringify({schemaVersion:2,claimedIds,claimedAt}))},[claimedIds,claimedAt,hydrated]);const activationFor=(event:CharacterStoryEvent)=>event.unlocksAfterEventId?claimedAt[event.unlocksAfterEventId]:undefined;const requiredBondFor=(event:CharacterStoryEvent)=>getStoryEventPlacement(event.id)?.requiredBondLevel??1;const isLocked=(event:CharacterStoryEvent)=>Boolean((event.unlocksAfterEventId&&!claimedIds.includes(event.unlocksAfterEventId))||getAffinityLevel(affinity.points[event.characterId]??0)<requiredBondFor(event));useEffect(()=>{if(!hydrated)return;getActiveContentPack().events.forEach((event)=>{if(isLocked(event)||claimedIds.includes(event.id))return;const progress=getStoryProgress(event,events,activationFor(event));progress.objectives.forEach((objective,index)=>{if(!objective.complete)return;const copy=event.stageMails[index];if(copy)affinity.deliverMail({id:`story-${event.id}-${index+1}`,characterId:event.characterId,kind:"event",sentAt:new Date().toISOString(),...copy})})})},[events,hydrated,affinity,claimedIds,claimedAt]);const value=useMemo<StoryValue>(()=>({claimedIds,getActiveEvent:(characterId)=>{const sequence=getStoryEvents(characterId);return sequence.find((event)=>!claimedIds.includes(event.id)&&!isLocked(event))??sequence.find((event)=>!claimedIds.includes(event.id))??sequence.at(-1)},getState:(event)=>({...getStoryProgress(event,events,activationFor(event)),claimed:claimedIds.includes(event.id),locked:isLocked(event),requiredBondLevel:requiredBondFor(event)}),claim:(event)=>{if(isLocked(event))return false;const progress=getStoryProgress(event,events,activationFor(event));if(!progress.completed||claimedIds.includes(event.id))return false;const now=new Date().toISOString();setClaimedIds((current)=>[...current,event.id]);setClaimedAt((current)=>({...current,[event.id]:now}));account.addLifeReward(event.rewardBubbles,120);affinity.award(event.characterId,event.rewardBond,"journey",`story-${event.id}`);return true}}),[events,claimedIds,claimedAt,account,affinity]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useStoryEvents(){const value=useContext(Context);if(!value)throw new Error("useStoryEvents must be used inside StoryEventsProvider");return value}
