export const BACKUP_SCHEMA_VERSION = 2;
export const BACKUP_KEYS = ["ip-alive:game-progress:v3", "ip-alive:character-progress:v2", "ip-alive:life-progress:v2", "ip-alive:profile:v1", "ip-alive:activity-ledger:v1", "ip-alive:story-events:v1", "ip-alive:chat-history:v1", "ip-alive:unlocks:v1"] as const;
export type BackupKey = typeof BACKUP_KEYS[number];
export interface BackupPayload { product: "ip-alive"; schemaVersion: number; exportedAt: string; data: Record<BackupKey, string | null>; checksum: string; }

export function checksumFor(value: string) { let hash = 2166136261; for (let index = 0; index < value.length; index += 1) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, "0"); }
const checksumInput = (payload: Omit<BackupPayload, "checksum">) => JSON.stringify(payload);
export function createBackupPayload(data: Record<BackupKey, string | null>, exportedAt = new Date().toISOString()): BackupPayload { const base = { product: "ip-alive" as const, schemaVersion: BACKUP_SCHEMA_VERSION, exportedAt, data }; return { ...base, checksum: checksumFor(checksumInput(base)) }; }
function migrateGameProgress(raw:string|null|undefined){if(!raw)return null;const value=JSON.parse(raw) as Record<string,unknown>;return JSON.stringify({...value,schemaVersion:3,completedLevelIds:Array.isArray(value.completedLevelIds)?value.completedLevelIds:[],bestLevelScores:value.bestLevelScores??{},levelStars:value.levelStars??{}})}
export function parseBackupPayload(raw: string): BackupPayload { const parsed = JSON.parse(raw) as {product?:string;schemaVersion?:number;exportedAt?:string;data?:Record<string,string|null>;checksum?:string}; if (parsed.product !== "ip-alive") throw new Error("wrong-product"); if (parsed.schemaVersion !== 1&&parsed.schemaVersion!==BACKUP_SCHEMA_VERSION) throw new Error("unsupported-version"); if (!parsed.exportedAt || !parsed.data || typeof parsed.data !== "object" || !parsed.checksum) throw new Error("missing-fields"); const sourceBase={product:parsed.product,schemaVersion:parsed.schemaVersion,exportedAt:parsed.exportedAt,data:parsed.data};if(checksumFor(JSON.stringify(sourceBase))!==parsed.checksum)throw new Error("checksum-mismatch"); Object.values(parsed.data).forEach((value)=>{if(value!==null&&typeof value!=="string")throw new Error("invalid-data");if(value)JSON.parse(value)}); const data=Object.fromEntries(BACKUP_KEYS.map((key)=>[key,key==="ip-alive:game-progress:v3"?(parsed.schemaVersion===BACKUP_SCHEMA_VERSION&&key in parsed.data!?parsed.data![key]:migrateGameProgress(parsed.data![key]??parsed.data!["ip-alive:game-progress:v2"]??parsed.data!["ip-alive:game-progress:v1"])):parsed.data![key]??null])) as Record<BackupKey,string|null>;return parsed.schemaVersion===BACKUP_SCHEMA_VERSION?parsed as BackupPayload:createBackupPayload(data,parsed.exportedAt); }
