export interface CharacterGrowthStage { bondLevel:number; titleEn:string; titleZh:string; detailEn:string; detailZh:string; }
export interface OriginalCharacterCanon { characterId:string; originEn:string; originZh:string; personality:string[]; coreValues:string[]; growth:CharacterGrowthStage[]; }
export const originalCharacterCanon:Record<string,OriginalCharacterCanon>={
  yunzhou:{characterId:"yunzhou",originEn:"A scholar from a poor family who placed second in the imperial examination and now serves as a seventh-rank Hanlin Academy editor.",originZh:"寒门出身，进京赶考高中榜眼，现任正七品翰林院编修。",personality:["benevolent","restrained","steadfast","righteous"],coreValues:["the welfare of ordinary people","justice before personal gain","learning as public duty"],growth:[
    {bondLevel:1,titleEn:"Hanlin Academy Editor · Rank 7",titleZh:"正七品·翰林院编修",detailEn:"His first appointment after placing second in the imperial examination.",detailZh:"高中榜眼后的初授官职。"},{bondLevel:2,titleEn:"Piling Provincial Examiner",titleZh:"毗陵乡试主考",detailEn:"Entrusted to select talent with fairness.",detailZh:"奉命主持乡试，以公正选拔人才。"},{bondLevel:3,titleEn:"Left Assistant Expositor",titleZh:"左春坊左赞善",detailEn:"Begins advising within the Eastern Palace.",detailZh:"入左春坊，开始承担辅导与规谏之责。"},{bondLevel:4,titleEn:"Compiler of the State History",titleZh:"史书编修",detailEn:"Records the age without bending truth for power.",detailZh:"参与修史，不因权势曲笔。"},{bondLevel:5,titleEn:"Lecturer-in-waiting",titleZh:"侍讲学士",detailEn:"Expounds the classics and speaks when silence would be easier.",detailZh:"讲论经义，也在沉默更容易时选择直言。"},{bondLevel:6,titleEn:"Director of the Court of the Heir Apparent",titleZh:"詹事府詹事",detailEn:"Takes responsibility for the Eastern Palace.",detailZh:"统理詹事府，承担东宫教育与政务之责。"},{bondLevel:7,titleEn:"Grand Secretariat Academician & Vice Minister of Rites",titleZh:"南书房内阁学士兼礼部侍郎",detailEn:"Enters the center of government without forgetting ordinary lives.",detailZh:"进入中枢，仍不忘民间疾苦。"},{bondLevel:8,titleEn:"Left Censor-in-chief · Rank 1b",titleZh:"从一品·都察院左都御史",detailEn:"Oversees officials and confronts abuse of power.",detailZh:"总宪百官，纠察不法，直面权势。"},{bondLevel:9,titleEn:"Minister of Justice · Rank 1b",titleZh:"从一品·刑部尚书",detailEn:"His final office places law, mercy and justice in his hands.",detailZh:"执掌刑部，在律法、仁恕与公义之间作出抉择。"}]},
  mia:{characterId:"mia",originEn:"An upbeat, sometimes careless INFP studying law at the fictional Wudong University. Relaxed in life, uncompromising at work.",originZh:"吴东大学（虚构）法律系本科在读。INFP，性格开朗，生活里甚至有些大大咧咧，但对工作极其认真。",personality:["open","optimistic","spontaneous","conscientious at work"],coreValues:["empathy","professional responsibility","standing beside real people"],growth:[
    {bondLevel:1,titleEn:"Law Undergraduate",titleZh:"法律系本科生",detailEn:"Learning how ideals meet real cases.",detailZh:"开始理解理想如何面对真实案件。"},{bondLevel:2,titleEn:"Postgraduate Candidate",titleZh:"法学考研生",detailEn:"Prepares seriously despite a chaotic schedule.",detailZh:"日程依旧有些乱，但备考从不含糊。"},{bondLevel:3,titleEn:"Master's Student in Law",titleZh:"法学硕士研究生",detailEn:"Builds deeper professional judgment.",detailZh:"建立更扎实的专业判断。"},{bondLevel:4,titleEn:"Red-circle Firm Intern",titleZh:"红圈所实习生",detailEn:"Meets the pressure of elite legal practice.",detailZh:"第一次真正面对顶尖律所的工作强度。"},{bondLevel:5,titleEn:"Associate Lawyer",titleZh:"律所执业律师",detailEn:"Earns a full-time place through careful work.",detailZh:"凭认真与可靠获得正式职位。"},{bondLevel:6,titleEn:"Senior Associate",titleZh:"高级律师",detailEn:"Begins leading matters and mentoring younger colleagues.",detailZh:"开始主导项目，也开始带领新人。"},{bondLevel:7,titleEn:"Law Firm Partner",titleZh:"律所合伙人",detailEn:"Keeps her warmth while becoming responsible for a team and its clients.",detailZh:"成为合伙人后，仍保留温度，也承担团队与客户的责任。"}]},
  nova:{characterId:"nova",originEn:"Retired captain of Earth Fleet Ship 243. An INTJ commander who acts decisively and puts efficiency first.",originZh:"地球舰队243舰退役舰长。INTJ，杀伐果断，效率为先。",personality:["decisive","strategic","controlled","efficiency-first"],coreValues:["mission survival","clear responsibility","results grounded in evidence"],growth:[
    {bondLevel:1,titleEn:"Retired Captain · Access Restricted",titleZh:"退役舰长·限制访问",detailEn:"Acknowledges you as a civilian contact, not yet a confidant.",detailZh:"将你视为民用联系人，尚未交付信任。"},{bondLevel:3,titleEn:"Trusted Communications Link",titleZh:"可信通信对象",detailEn:"Shares selected records from Ship 243.",detailZh:"开始向你开放243舰的部分记录。"},{bondLevel:5,titleEn:"Timeline-cleared Companion",titleZh:"获准跨时空同行",detailEn:"Authorizes a present-era crossing despite the inefficiency.",detailZh:"即使认为这个时代低效，仍批准与你跨时空同行。"},{bondLevel:7,titleEn:"Captain's Final Confidant",titleZh:"舰长的最终知情人",detailEn:"Reveals the decision that ended the last mission of Ship 243.",detailZh:"向你公开243舰最后一次任务结束时的决定。"}]}}
export function getCharacterCanon(id:string){return originalCharacterCanon[id]}
export function getCharacterGrowth(id:string,bondLevel:number){const canon=getCharacterCanon(id);if(!canon)return undefined;return [...canon.growth].reverse().find((stage)=>bondLevel>=stage.bondLevel)??canon.growth[0]}
