import type { ActivityEvent, ActivityType } from "@/features/progression";

export interface StoryObjective { type:ActivityType; target:number; labelEn:string; labelZh:string; }
export interface CharacterStoryEvent { id:string; characterId:string; titleEn:string; titleZh:string; premiseEn:string; premiseZh:string; objectives:StoryObjective[]; rewardBubbles:number; rewardBond:number; stageMails:{subjectEn:string;subjectZh:string;bodyEn:string;bodyZh:string}[]; }
export const characterStoryEvents:CharacterStoryEvent[]=[
  {id:"yunzhou-examination",characterId:"yunzhou",titleEn:"The Piling Examination",titleZh:"毗陵衡文",premiseEn:"Yunzhou has been named chief examiner. He asks you to witness how he protects fairness when influence reaches the examination hall.",premiseZh:"云舟奉命出任毗陵乡试主考。他邀你见证：当权势伸入贡院时，他将如何守住取士公正。",rewardBubbles:180,rewardBond:80,objectives:[{type:"chat",target:3,labelEn:"Discuss the appointment",labelZh:"与云舟讨论主考之责"},{type:"mail-read",target:2,labelEn:"Read examination letters",labelZh:"阅读乡试来信"},{type:"task-completed",target:2,labelEn:"Complete duties together",labelZh:"共同完成两项事务"}],stageMails:[{subjectEn:"The seal of the examiner",subjectZh:"主考之印",bodyEn:"The appointment has arrived. Talent must not be buried by poverty, nor lifted by a powerful surname. I know this because I once entered the capital with little more than books.",bodyZh:"任命已至。才学不可因寒门而埋没，也不可因显姓而虚高。我明白这一点，因为当年入京时，我所有的也不过几卷书。"},{subjectEn:"A name on the list",subjectZh:"名册上的姓氏",bodyEn:"Someone asked that I look kindly upon a particular name. Kindness belongs to people; favoritism does not belong in an examination. I returned the note unanswered.",bodyZh:"有人托我对名册中的一个姓氏多加照拂。仁厚当施于百姓，徇私却不可入贡院。我未作答复，只将字条原样退回。"},{subjectEn:"When the gates open",subjectZh:"贡院开门之日",bodyEn:"The papers are sealed. When the gates open, some will rejoice and some will return home. I can promise only this: every name was weighed by the same measure.",bodyZh:"试卷已经封存。贡院开门后，有人欢喜，也有人归乡。我只能许诺一件事：每一个名字，都用同一把尺衡量。"}]},
  {id:"mia-moot-court",characterId:"mia",titleEn:"The Moot Court File",titleZh:"模拟法庭案卷",premiseEn:"Mia volunteered for the hardest part of a university moot court. Her notes are chaotic; her preparation is not.",premiseZh:"米娅主动接下了吴东大学模拟法庭中最难的部分。她的桌面依然很乱，但准备工作绝不含糊。",rewardBubbles:160,rewardBond:75,objectives:[{type:"chat",target:3,labelEn:"Prepare the argument",labelZh:"陪米娅梳理论点"},{type:"game-completed",target:2,labelEn:"Train under pressure",labelZh:"共同完成两局压力训练"},{type:"task-completed",target:2,labelEn:"Finish preparation tasks",labelZh:"完成两项准备任务"}],stageMails:[{subjectEn:"Do not look at my desk",subjectZh:"先别看我的桌子",bodyEn:"The case file is somewhere under three highlighters and an empty coffee cup. Yes, it looks bad. No, the argument is not bad. Give me twenty minutes.",bodyZh:"案卷就在三支荧光笔和一个空咖啡杯下面。对，桌面看起来很糟；不，论点一点也不糟。给我二十分钟。"},{subjectEn:"The question I missed",subjectZh:"我漏掉的那个问题",bodyEn:"I was so busy proving our side that I nearly stopped seeing the person on the other side. That is exactly how legal work goes wrong. I rewrote the argument.",bodyZh:"我刚才只顾着证明我方立场，差点看不见对面那个真实的人。法律工作就是这样开始走偏的。我把论证重写了。"},{subjectEn:"After the hearing",subjectZh:"庭审结束以后",bodyEn:"We did not win every score. But when the judge pressed us, I knew why every sentence was there. I think that matters more than looking confident.",bodyZh:"我们没有拿到每一项最高分。但法官追问时，我知道每句话为什么写在那里。我觉得这比看起来很自信更重要。"}]},
  {id:"nova-ship-243",characterId:"nova",titleEn:"Ship 243 · Partial Declassification",titleZh:"243舰·部分解密",premiseEn:"Nova authorizes a controlled reconstruction of Ship 243's final route. Every interaction restores another fragment.",premiseZh:"诺瓦批准对243舰最后航线进行受控复原。每一次互动都会恢复一段记录。",rewardBubbles:220,rewardBond:90,objectives:[{type:"chat",target:3,labelEn:"Complete command interviews",labelZh:"完成三次舰长访谈"},{type:"game-completed",target:3,labelEn:"Run tactical simulations",labelZh:"完成三次战术模拟"},{type:"mail-read",target:2,labelEn:"Read restored transmissions",labelZh:"阅读两封复原通信"}],stageMails:[{subjectEn:"243 / Command access",subjectZh:"243舰／指挥权限",bodyEn:"You requested the final route. Request conditionally approved. Do not romanticize what follows. Command is the practice of choosing which loss remains survivable.",bodyZh:"你申请查阅最后航线。申请有条件批准。不要浪漫化接下来的内容。所谓指挥，就是判断哪一种损失仍可承受。"},{subjectEn:"243 / Missing seventeen minutes",subjectZh:"243舰／缺失的十七分钟",bodyEn:"Seventeen minutes are absent from the public log. That was not data corruption. I ordered the deletion. At the time, preserving the fleet mattered more than preserving my reputation.",bodyZh:"公开日志中缺失了十七分钟。那不是数据损坏，是我下令删除的。当时，保全舰队比保全我的名誉更重要。"},{subjectEn:"243 / One surviving signal",subjectZh:"243舰／唯一幸存的信号",bodyEn:"One signal crossed the interference after the ship went dark. I have not opened it since retirement. Complete the reconstruction, and I will open it with you.",bodyZh:"全舰熄灭后，只有一道信号穿过干扰抵达。我退役后从未打开它。完成复原，我会与你一起开启。"}]},
];
export function getStoryEvent(characterId:string){return characterStoryEvents.find((event)=>event.characterId===characterId)}
export function getStoryProgress(event:CharacterStoryEvent,events:ActivityEvent[]){const objectives=event.objectives.map((objective)=>{const count=events.filter((item)=>item.characterId===event.characterId&&item.type===objective.type).length;return{...objective,current:Math.min(count,objective.target),complete:count>=objective.target}});return{objectives,completed:objectives.every((item)=>item.complete),completedCount:objectives.filter((item)=>item.complete).length}}
